services:
  doctrine_multilingual.initializer:
    class: Keym\MultilingualBundle\EventListener\DoctrineMultilingualInitializer
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 1024 }

  Keym\MultilingualBundle\Service\MultilingualService:
    class: Keym\MultilingualBundle\Service\MultilingualService
    autowire: true

